[package]
name = "tile_net"
version = "1.0.0"
authors = ["Bourgond Aries <macocio@gmail.com>"]

[dependencies]
clippy = { version = "0.0", optional = true }
interleave = "1.0"

[features]
default = []
dev = ["clippy"]

[dev-dependencies]
sfml = "0.11.2"
