[package]
name = "tile_net"
version = "0.1.0-alpha"
authors = ["Bourgond Aries <macocio@gmail.com>"]

[dependencies]
clippy = {version = "0.0.77", optional = true}
interleave = "0.2.3"

[features]
default = []
dev = ["clippy"]
